/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.List;

public class StudentManagerTest {

    @Test
    public void testAddStudent() {
        StudentManager manager = new StudentManager();
        Student s = new Student("Alice", 101);
        manager.addStudent(s);

        // This part assumes you add a getter method in StudentManager to fetch students
        List<Student> students = manager.getStudents(); 
        assertEquals(1, students.size());
        assertEquals("Alice", students.get(0).getName());
        assertEquals(101, students.get(0).getRoll());
    }

    @Test
    public void testDisplayStudentsWhenEmpty() {
        StudentManager manager = new StudentManager();
        assertTrue(manager.getStudents().isEmpty());
    }
}
